# Generated by Django 5.2.3 on 2025-06-28 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('document', 'Document')], max_length=50)),
                ('file', models.FileField(upload_to='media/')),
                ('news', models.ManyToManyField(related_name='media_files', to='news.news')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
                ('news', models.ManyToManyField(related_name='tags', to='news.news')),
            ],
        ),
    ]
